#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");

function read(rel) {
  return fs.readFileSync(path.join(root, rel), "utf8");
}
function must(hay, needle, label) {
  if (!hay.includes(needle)) throw new Error("missing " + label + ": " + needle);
}
function mustNot(hay, needle, label) {
  if (hay.includes(needle)) throw new Error("invented " + label + ": " + needle);
}

const tip = read("aia-tip.js");
const supportTalk = read("support-talk.js");
const support = read("support.html");
const help = read("help.html");
const theme = read("theme.css");
const yesNo = read("ACCOUNT-YES-NO.md");
const packMd = read("PACK.md");
const pkg = read("package.json");

must(tip, "Ask AIA", "shared Ask AIA");
must(tip, "support.html?ask=", "Ask AIA opens Help chat");
must(tip, "&tip=", "Ask AIA sends plain tip text");
must(tip, "&field=", "Ask AIA sends field id");
must(tip, "&from=", "Ask AIA sends page");
must(tip, "function context", "Ask AIA context payload");
must(tip, "window.AIATip", "AIATip export");
must(tip, '"desk-name"', "desk-name tip");
must(tip, '"desk-code"', "desk-code tip");
must(tip, '"give-pack"', "give-pack tip");
must(tip, '"update-pack"', "update-pack tip");
must(tip, '"drop-title"', "drop-title tip");
must(tip, '"drop-need"', "drop-need tip");
must(tip, '"drop-who"', "drop-who tip");
must(tip, '"drop-kind"', "drop-kind tip");
must(tip, '"drop-phone"', "drop-phone tip");
must(tip, '"drop-photo"', "drop-photo tip");
must(tip, '"drop-paste"', "drop-paste tip");
must(tip, '"drop-tell"', "drop-tell tip");
must(tip, '"drop-kind-need"', "drop-kind-need tip");
must(tip, '"drop-kind-when"', "drop-kind-when tip");
must(tip, '"drop-outcome"', "drop-outcome tip");
must(tip, '"drop-kind-where"', "drop-kind-where tip");
must(tip, '"drop-kind-who-for"', "drop-kind-who-for tip");
must(tip, '"drop-kind-from"', "drop-kind-from tip");
must(tip, '"drop-kind-amount"', "drop-kind-amount tip");
must(tip, '"drop-kind-callback"', "drop-kind-callback tip");
must(tip, "Public drop never sees money, Stop, or People", "drop-who public honesty");
must(tip, "Desk does not dial or send from here", "drop-phone no silent send");
must(tip, "They ride on the card", "drop-photo rides on card");
mustNot(tip, "The desk writes a card from it", "drop-paste still says the desk writes");
must(tip, "A Desk AI drafts the card from it", "drop-paste Desk AI drafts");
must(tip, "You still tap Yes or Stop before anything leaves", "drop-paste Yes or Stop");
mustNot(tip, "What should the desk do with it?", "drop-tell still says What should the desk do");
mustNot(tip, "Tell the desk the next draft", "drop-tell still says Tell the desk the next draft");
must(tip, "What should a Desk AI draft?", "drop-tell Desk AI draft title");
must(tip, "Tell a Desk AI the next draft", "drop-tell Desk AI draft only");
must(yesNo, "Drop Put data on Tell leftover after that pass", "ACCOUNT-YES-NO names Drop Put data on Tell leftover");
must(packMd, "Drop Put data on Tell leftover:", "PACK.md names Drop Put data on Tell leftover");
must(tip, "Extra note for this kind", "drop-kind-need lands on card");
must(tip, "Optional time on the card", "drop-kind-when optional time");
mustNot(tip, "What the desk should do next", "drop-outcome still says What the desk should do next");
must(tip, "What a Desk AI should draft next", "drop-outcome Desk AI draft next");
must(yesNo, "Drop Preferred outcome leftover after that pass", "ACCOUNT-YES-NO names Drop Preferred outcome leftover");
must(packMd, "Drop Preferred outcome leftover:", "PACK.md names Drop Preferred outcome leftover");
must(tip, "Optional place on the card", "drop-kind-where optional place");
must(tip, "Who this drop is for", "drop-kind-who-for optional name");
must(tip, "Optional start place on the card", "drop-kind-from optional start");
must(tip, "A note, not a charge", "drop-kind-amount not a charge");
must(tip, "Why does this kind ask for a callback number?", "drop-kind-callback ask");
must(tip, '"support-title"', "support-title tip");
must(tip, '"support-broke"', "support-broke tip");
must(tip, '"connect-wallet"', "connect-wallet tip");
must(tip, "When → If → Then on this desk queue", "give-pack When-If-Then queue");
must(tip, "Buyer binds their own keys", "give-pack buyer keys");
must(tip, "Webhook is the live pipe", "give-pack webhook near lane");
must(tip, "Not Wallet.AIA", "tip wallet honesty");
must(tip, "Collect stays HOLD", "tip Collect HOLD");
mustNot(tip, "Zendesk", "tip Zendesk");
mustNot(tip, "drop-pack.js", "tip loads drop-pack.js");
mustNot(tip, "AIA coin", "tip AIA coin");
mustNot(tip, "collecting ETH", "tip ETH collect");
mustNot(tip, "future Pack", "tip future Pack SKU");
mustNot(tip, "Pack partners", "tip pack partners market");
mustNot(tip, "escrow", "tip ETH escrow");
mustNot(tip, "micro-wei", "tip micro-wei billing");
mustNot(tip, "streaming ETH", "tip streaming ETH");
mustNot(tip, "state channel", "tip L2 state channel");
mustNot(tip, "NFT", "tip pack NFT license");
mustNot(tip, "DID login", "tip DID login");
mustNot(tip, "governance token", "tip governance token");
mustNot(tip, "IoT", "tip IoT marketplace");
mustNot(tip, "robotics", "tip robotics labor");
mustNot(tip, "humanoid", "tip humanoid labor");
mustNot(tip, "virtual phone", "tip virtual phone numbers");

must(theme, ".aia-tip-pop", "theme paints tip popover");
must(theme, "button.aia-tip", "theme paints tip button");

["index.html", "how.html", "setup.html", "onboard.html", "drop.html", "login.html", "widget.html", "account.html", "examples.html", "help.html", "support.html", "pipes.html", "connections.html", "create.html"].forEach(function (name) {
  const html = read(name);
  must(html, "aia-tip.js", name + " loads aia-tip.js");
  must(html, "data-aia-tip", name + " has a field tip");
  mustNot(html, "drop-pack.js", name + " loads drop-pack.js");
  mustNot(html, "Zendesk", name + " Zendesk");
  mustNot(html, "AIA coin", name + " AIA coin");
  mustNot(html, "escrow", name + " ETH escrow");
  mustNot(html, "micro-wei", name + " micro-wei billing");
  mustNot(html, "streaming ETH", name + " streaming ETH");
  mustNot(html, "state channel", name + " L2 state channel");
  mustNot(html, "trustless", name + " trustless escrow");
  mustNot(html, "DID login", name + " DID login");
  mustNot(html, "governance token", name + " governance token");
});

const onboard = read("onboard.html");
must(onboard, 'data-aia-tip="desk-name"', "onboard Desk name tip");
must(onboard, 'data-aia-tip="desk-code"', "onboard Desk code tip");
must(onboard, "not a mint lesson", "onboard does not teach mint");

must(read("how.html"), 'data-aia-tip="week-shop"', "how week field tip");
must(read("how.html"), 'data-aia-tip="update-pack"', "how Update pack tip");
must(read("index.html"), 'data-aia-tip="card-taps"', "home card-taps tip");
must(read("index.html"), 'data-aia-tip="update-pack"', "home Update pack tip");
must(read("setup.html"), 'data-aia-tip="practice-card"', "setup practice tip");
must(read("setup.html"), 'data-aia-tip="update-pack"', "setup Update pack tip");
must(read("drop.html"), 'data-aia-tip="desk-name"', "drop Desk name tip");
must(read("drop.html"), 'data-aia-tip="desk-code"', "drop Desk code tip");
must(read("drop.html"), 'data-aia-tip="drop-title"', "drop Title tip");
must(read("drop.html"), 'data-aia-tip="drop-need"', "drop need tip");
must(read("drop.html"), 'data-aia-tip="drop-who"', "drop I am tip");
must(read("drop.html"), 'data-aia-tip="drop-kind"', "drop kind tip");
must(read("drop.html"), 'data-aia-tip="drop-phone"', "drop phone tip");
must(read("drop.html"), 'data-aia-tip="drop-photo"', "drop photo tip");
must(read("drop.html"), 'data-aia-tip="drop-paste"', "drop paste tip");
must(read("drop.html"), 'data-aia-tip="drop-tell"', "drop tell tip");
must(read("widget.html"), 'data-aia-tip="desk-name"', "widget Desk name tip");
must(read("widget.html"), 'data-aia-tip="drop-title"', "widget Title tip");
must(read("widget.html"), 'data-aia-tip="drop-who"', "widget I am tip");
must(read("widget.html"), 'data-aia-tip="drop-kind"', "widget kind tip");
must(read("widget.html"), 'data-aia-tip="drop-phone"', "widget phone tip");
must(read("widget.html"), 'data-aia-tip="drop-photo"', "widget photo tip");
must(read("widget.html"), 'data-aia-tip="drop-paste"', "widget paste tip");
must(read("widget.html"), 'data-aia-tip="drop-tell"', "widget tell tip");
must(read("drop-agent.js"), '"drop-kind-need"', "kind-fields What is needed tip id");
must(read("drop-agent.js"), '"drop-kind-when"', "kind-fields When tip id");
must(read("drop-agent.js"), '"drop-outcome"', "kind-fields outcome tip id");
must(read("drop-agent.js"), '"drop-kind-where"', "kind-fields Where tip id");
must(read("drop-agent.js"), '"drop-kind-who-for"', "kind-fields Who it is for tip id");
must(read("drop-agent.js"), '"drop-kind-from"', "kind-fields From tip id");
must(read("drop-agent.js"), '"drop-kind-amount"', "kind-fields Amount note tip id");
must(read("drop-agent.js"), '"drop-kind-callback"', "kind-fields Callback number tip id");
must(read("drop-agent.js"), "data-aia-tip=", "kind-fields paint data-aia-tip");
must(read("drop-agent.js"), 'class=\\"aia-tip\\"', "kind-fields paint aia-tip button");
must(read("drop.html"), "drop-agent.js", "drop loads kind-field paint");
must(read("widget.html"), "drop-agent.js", "widget loads kind-field paint");
must(read("account.html"), 'data-aia-tip="give-pack"', "account Give pack tip");
must(read("account.html"), 'data-aia-tip="update-pack"', "account Update pack tip");
must(read("account.html"), ">Give pack<", "account Give pack CTA");
must(read("account.html"), ">Update pack<", "account Update pack CTA");
must(read("examples.html"), ">Give pack<", "examples Give pack CTA");
must(read("examples.html"), ">Update pack<", "examples Update pack CTA");
must(read("examples.html"), 'data-aia-tip="give-pack"', "examples Give pack tip");
must(read("help.html"), ">Give pack<", "help Give pack CTA");
must(read("help.html"), ">Update pack<", "help Update pack CTA");
must(read("help.html"), 'data-aia-tip="give-pack"', "help Give pack tip");
must(read("help.html"), "A pack puts When → If → Then on this desk queue", "help pack When-If-Then");
must(read("help.html"), "Buyer binds their own keys", "help pack buyer keys");
must(read("help.html"), "Webhook is the live pipe", "help webhook near lane");
must(read("support.html"), 'data-aia-tip="support-title"', "support Title tip");
must(read("support.html"), 'data-aia-tip="support-broke"', "support What-broke tip");
must(read("support.html"), 'data-aia-tip="support-page"', "support page tip");
must(tip, '"pipes"', "pipes tip");
must(tip, "Webhook is live", "pipes webhook live");
must(tip, "Log in opens the vendor", "pipes login opens vendor");
must(read("pipes.html"), 'data-aia-tip="pipes"', "pipes page pipes tip");
must(read("pipes.html"), 'data-aia-tip="desk-name"', "pipes Desk name tip");
must(read("pipes.html"), 'data-aia-tip="desk-code"', "pipes Desk code tip");
must(read("connections.html"), 'data-aia-tip="pipes"', "connections page pipes tip");
must(read("connections.html"), 'data-aia-tip="desk-name"', "connections Desk name tip");
must(read("connections.html"), 'data-aia-tip="desk-code"', "connections Desk code tip");
must(tip, '"desk-ai"', "desk-ai tip");
must(tip, "Name a desk AI", "desk-ai names a desk AI");
must(tip, "Desk AIs that draft", "desk-ai tagline drafts");
must(tip, "Humans that decide", "desk-ai tagline humans");
must(tip, "Draft ready. I cannot send, pay, or bind anything. You stay in control.", "desk-ai firm draft-only");
must(tip, "Yes / Stop / Kill stay human", "desk-ai Yes Stop Kill human");
must(tip, "not a free-roaming MVP bot", "desk-ai not MVP bot");
must(tip, "Drafts the next step and the words", "desk-ai next step");
must(yesNo, "Desk AI canon leftover", "ACCOUNT-YES-NO names Desk AI canon leftover");
must(packMd, "Desk AI canon leftover", "PACK.md names Desk AI canon leftover");
must(yesNo, "Desk AI voice leftover", "ACCOUNT-YES-NO names Desk AI voice leftover");
must(packMd, "Desk AI voice leftover", "PACK.md names Desk AI voice leftover");
must(yesNo, "Drop Put data on leftover after that pass", "ACCOUNT-YES-NO names Drop Put data on leftover");
must(packMd, "Drop Put data on leftover:", "PACK.md names Drop Put data on leftover");
must(read("create-desk.js"), 'data-aia-tip="desk-ai"', "create Name this desk AI tip");
must(read("create-desk.js"), "Desk AIs that draft. Humans that decide.", "create Desk AI pick tagline");
must(read("create-desk.js"), "Draft ready. I cannot send, pay, or bind anything. You stay in control.", "create Desk AI helper firm");
must(read("create.html"), "aia-tip.js", "create loads aia-tip.js");
must(read("create.html"), 'data-aia-tip="drop-kind"', "create start What is it tip");
must(read("create.html"), 'data-aia-tip="drop-need"', "create start How / what tip");
must(read("create.html"), "Desk AIs that draft. Humans that decide.", "create lead tagline");
must(read("developer.js"), 'data-aia-tip=\\"desk-ai\\"', "studio AI name tip");
must(read("developer.js"), "Draft ready. I cannot send, pay, or bind anything. You stay in control.", "studio Desk AI helper firm");
must(read("developer.html"), "aia-tip.js", "studio loads aia-tip.js");
mustNot(read("developer.html"), "drop-pack.js", "studio loads drop-pack.js");
mustNot(read("developer.html"), "AIA coin", "studio AIA coin");
mustNot(read("developer.html"), "escrow", "studio ETH escrow");
must(read("consign.html"), ">Drop it<", "consign Drop it not Send to engine");
mustNot(read("consign.html"), "Send to engine", "consign Send-to-engine jargon");
mustNot(read("consign.html"), ">Approve<", "consign Approve as Yes");

must(supportTalk, "paintAsk", "Help chat reads Ask AIA");
must(supportTalk, 'q.get("field")', "Help chat field");
must(supportTalk, 'q.get("ask")', "Help chat ask");
must(supportTalk, 'q.get("tip")', "Help chat plain tip text");
must(supportTalk, "askCtx", "Help chat keeps Ask AIA context");
must(supportTalk, "field: p.field", "Admin card keeps field id");
must(supportTalk, "tip: p.tip", "Admin card keeps tip text");
must(supportTalk, "This chat stays draft / help", "Help chat stays draft first");
must(supportTalk, "Need a person? Drop a card on the AIA Admin desk", "Help chat human card");
must(supportTalk, "Yes / Stop stay human", "Help chat Yes / Stop human");
must(supportTalk, "AIATip", "Help chat uses shared tips");
must(supportTalk, "HOME = line", "Ask AIA becomes Quiet home");
must(supportTalk, "thread(HOME)", "Quiet restores Ask AIA or stock prompt");
mustNot(supportTalk, "thread(PROMPT)", "Quiet does not wipe Ask AIA to the stock prompt");
must(support, "aia-tip.js", "support loads shared tips");
must(support, "Ask AIA answers here first", "support Ask AIA draft first");
must(support, "Drop a card on the AIA Admin desk", "support Admin card");
must(support, "Yes / Stop stay human", "support Yes / Stop human");
must(support, "Not a ticket portal", "support not Zendesk");
must(help, "move as cards between your desk and the AIA Admin desk", "help card bridge");
mustNot(support, "Zendesk", "support Zendesk");
mustNot(help, "Zendesk", "help Zendesk");
mustNot(supportTalk, "escrow", "Help chat ETH escrow");
mustNot(support, "escrow", "support ETH escrow");

must(yesNo, "check-aia-tip.js", "ACCOUNT-YES-NO records tip honesty");
must(yesNo, "Help chat Quiet leftover", "ACCOUNT-YES-NO names Quiet leftover");
must(yesNo, "Pipes field tips leftover", "ACCOUNT-YES-NO names Pipes field tips leftover");
must(yesNo, "Desk AI field tips leftover", "ACCOUNT-YES-NO names Desk AI field tips leftover");
must(packMd, "Ask AIA", "PACK.md names Ask AIA");
must(packMd, "Quiet on Help chat stops speech and keeps that answer", "PACK.md Quiet keeps Ask AIA");
must(packMd, "Pipes field tips leftover", "PACK.md names Pipes field tips leftover");
must(packMd, "Desk AI field tips leftover", "PACK.md names Desk AI field tips leftover");
must(pkg, "check-aia-tip.js", "package.json runs check-aia-tip");

console.log("check-aia-tip: ok");
