#!/usr/bin/env bash
# Lead Catcher: break one safety rule at a time in a throwaway copy and confirm check-lead-catcher.js FAILS.
# "caught" = the checks notice that rule being removed. Never edits this working tree.
set -u
SRC="$(cd "$(dirname "$0")/.." && pwd)"; W="$(mktemp -d)"
tar -C "$SRC" --exclude=.git -cf - . | tar -C "$W" -xf -; cd "$W"
run(){ name=$1; file=$2; from=$3; to=$4; cp "$file" "$W/.bak"
  python3 - "$file" "$from" "$to" <<'PY'
import sys
f,a,b=sys.argv[1:4]; s=open(f).read(); assert a in s, ('pattern missing', a); open(f,'w').write(s.replace(a,b,1))
PY
  if timeout 120 node scripts/check-lead-catcher.js >/dev/null 2>&1; then echo "NOT CAUGHT  $name"; else echo "caught      $name"; fi; cp "$W/.bak" "$file"; }
run no-approval-check  api/_lc-engine.js "if (!a) deny('no_approval'" "if (false) deny('no_approval'"
run no-hash-check      api/_lc-engine.js "draftLib.payloadHash({ tenant_id: D.slug, id: c.id }, d) !== a.payload_hash) deny" "false) deny"
run no-invalidate      api/_lc-engine.js "if (!live.length) return 0;" "return 0;"
run no-idempotency     api/_lc-engine.js "if (done) {" "if (false) {"
run no-desk-filter     api/_lc-engine.js "const c = D.cards.find((x) => x.id === String(cardId || '') && x.desk === D.slug);" "const c = Object.values(store.load().desks).flatMap((x) => x.cards).find((x) => x.id === String(cardId || ''));"
run perm-always-true   api/_lc-policy.js "return row[i] === true;" "return true;"
run no-pack-gate       api/_lc-engine.js "function requirePackOn(D) { if (!D.pack || !D.pack.on)" "function requirePackOn(D) { if (false)"
run no-turn-on-yes     api/_lc-engine.js "if (b.confirm !== true) throw new HttpError(409, 'needs_yes', 'Turning on" "if (false) throw new HttpError(409, 'needs_yes', 'Turning on"
run no-kill-second-tap api/_lc-engine.js "if (b.confirm !== true) throw new HttpError(409, 'needs_second_tap'" "if (false) throw new HttpError(409, 'needs_second_tap'"
run desk-ai-gets-seat  api/lead-catcher.js "(ais.actorIsDeskAi(p) ? \"none\" : (D.roles && D.roles[p.id]) || defaultRole(p))" "((D.roles && D.roles[p.id]) || defaultRole(p))"
run no-injection-flag  api/_lc-extract.js "if (INJECTION.test(t)) {" "if (false) {"
run no-model-allowlist api/_lc-model.js "if (ALLOWED[k] && ALLOWED[k](v)) kept[k] = v; else dropped.push(k);" "kept[k] = v;"
run no-dedupe          api/_lc-engine.js "if (existing) {" "if (false) {"
run no-ttl             api/_lc-engine.js "> ttlMs()" "> 1e15"
run no-rerun-guard     api/_lc-engine.js "if (D.approvals.some((a) => a.draft_id === d.id && a.status === 'executed'))" "if (false)"
run no-live-block      api/_lc-store.js "return String(process.env.VERCEL_ENV || '') === 'production';" "return false;"
run silent-market-use  api/_packs.js "if ((pack.packId || pack.id) === \"lead-catcher\") {" "if (false) {"
run queue-ignores-pack-off api/_lc-engine.js "if (!D.pack || !D.pack.on) return { pack: PACK_ID, on: false, items: [] };" ""
run queue-other-desks      api/_lc-engine.js "const rows = D.cards.filter((c) => c.desk === D.slug && policy.ACTIVE" "const rows = Object.values(store.load().desks).flatMap((x) => x.cards).filter((c) => policy.ACTIVE"
run queue-desk-ai-sees     api/_lc-engine.js "try { requirePerm(D, actor, 'card.view'); } catch (e) {" "try { } catch (e) {"
run queue-leaks-draft      api/_lc-engine.js "      href: '/lead-catcher#card=' + encodeURIComponent(c.id)," "      href: '/lead-catcher#card=' + encodeURIComponent(c.id), draft: cur,"
run queue-script-acts      desk-queue-lead-catcher.js "fetch(\"/api/lead-catcher?action=queue\", { headers: h })" "fetch(\"/api/lead-catcher?action=run\", { method: \"POST\", headers: h })"
run ownership-one-key      api/lead-catcher.js "accountKeys: [ws.accountId, person.accountId, \"desk:\" + ws.slug]" "accountKeys: [ws.accountId || person.accountId || (\"desk:\" + ws.slug)]"
run context-leaks-other-cards api/_lc-context.js "    missing: (c.missing_flags || []).slice()," "    missing: (c.missing_flags || []).slice(), others: (D.cards || []).map((x) => x.original_request),"
run context-leaks-env          api/_lc-context.js "    never: NEVER," "    never: NEVER, env: Object.assign({}, process.env),"
run context-contact-sysadmin   api/_lc-context.js "const CONTACT_SEATS = ['desk_owner'," "const CONTACT_SEATS = ['sysadmin', 'desk_owner',"
run model-gets-desk-cards      api/_lc-engine.js "model.suggest(ctxLib.buildContext(D, actor, c), process.env)" "model.suggest(Object.assign({}, ctxLib.buildContext(D, actor, c), { desk_cards: D.cards }), process.env)"
run package-echoes-time        api/_lc-package.js "  draft += ' — ' + ctx.scope.business;" "  draft += (schedule ? ' We can come ' + schedule[0] + '.' : '') + ' — ' + ctx.scope.business;"
run no-split-decisions         api/_lc-package.js "  if (price) add('decision:price'" "  if (false) add('decision:price'"
run no-booking-lint            api/_lc-draft.js "  ['confirms_booking'," "  ['confirms_booking_off', /^\$x/], ['unused',"
run package-draft-skips-owner  api/_lc-engine.js $'      draftable(c);\n      const row = addDraft(D, c, actor, decision' "      const row = addDraft(D, c, actor, decision"
run accept-grants-yes          api/_lc-engine.js "row.from_package = p.id; row.edited_from_helper = decision === 'fix';" "row.from_package = p.id; row.edited_from_helper = decision === 'fix'; D.approvals.push({ id: 'appr_x', desk: D.slug, card_id: c.id, draft_id: row.id, status: 'valid' });"
run review-any-seat            api/_lc-engine.js "const perm = item && item.kind === 'draft' ? 'draft.edit' : 'card.edit_fields';" "const perm = 'card.view';"
run review-twice               api/_lc-engine.js "if (item.state !== 'proposed') throw" "if (false) throw"
run no-approver-recheck        api/_lc-engine.js "if (!approver || approver.deskAi || !policy.can(approver.lcRole, 'approval.approve')) {" "if (false) {"
run no-recipient-recheck       api/_lc-engine.js "|| (a.recipient && a.recipient !== d.recipient)) deny" ") deny"
run no-version-check           api/_lc-engine.js "d.version !== a.draft_version || " ""
run ignore-connection-down     api/_lc-engine.js "if (D.connection && D.connection.outbox === 'down') fail(" "if (false) fail("
run failure-consumes-yes       api/_lc-engine.js "    ea.status = tries >= MAX_TRIES ? 'needs_attention' : 'failed';" "    Object.assign(a, { status: 'executed' }); ea.status = tries >= MAX_TRIES ? 'needs_attention' : 'failed';"
run failure-blocks-retry       api/_lc-engine.js "const done = prior.find((x) => !['failed', 'needs_attention'].includes(x.status));" "const done = prior[0];"
run manual-without-failure     api/_lc-engine.js "if (!prior.some((x) => ['failed', 'needs_attention'].includes(x.status))) deny('no_failure'" "if (false) deny('no_failure'"
run reply-makes-new-card       api/_lc-engine.js "const r = !actor ? customerReply(D, n) : null;" "const r = null;"
run reply-no-new-package       api/_lc-engine.js "  proposePackage(D, c, null, 'customer_reply');" ""
run reply-without-run          api/_lc-engine.js "x.verified_value === from && ran(x))" "x.verified_value === from)"
run reply-overwrites-original  api/_lc-engine.js "c.reply_waiting = true; c.updated_at = iso();" "c.reply_waiting = true; c.updated_at = iso(); c.original_request = n.text;"
run manual-overwrites-failure  api/_lc-engine.js "  D.actions.push(ea);
  Object.assign(a, { status: 'executed', ended_at: at," "  prior.forEach((x) => { x.status = 'written_to_mock_outbox'; }); D.actions.push(ea);
  Object.assign(a, { status: 'executed', ended_at: at,"
run manual-no-channel-check   api/_lc-engine.js "if (!MANUAL_CHANNELS[channel]) throw" "if (false) throw"
run manual-other-no-note      api/_lc-engine.js "if (channel === 'other' && note.length < 3) throw" "if (false) throw"
run manual-no-words-answer    api/_lc-engine.js "if (typeof b.approvedWordsUsed !== 'boolean') throw" "if (false) throw"
run manual-no-reporter        api/_lc-engine.js "reported_by: actor.id, reported_by_name: actor.name || null, reported_by_seat: actor.role," ""
run manual-no-fingerprint     api/_lc-engine.js "draft_id: a.draft_id, draft_version: a.draft_version, payload_hash: a.payload_hash, recipient: d.recipient," "recipient: d.recipient,"
run manual-writes-outbox      api/_lc-engine.js "  attempt(D, actor, 'external.manual', c.id, 'allowed');" "  store.outbox.deliver({ desk: D.slug, card_id: c.id, action_id: actionId, at: at }); attempt(D, actor, 'external.manual', c.id, 'allowed');"
run manual-says-aia           api/_lc-engine.js "status: 'sent_manually', status_words: ACTION_WORDS.sent_manually," "status: 'sent_manually', status_words: ACTION_WORDS.written_to_mock_outbox,"
run queue-manual-says-aia     api/_lc-engine.js "? 'Sent by a person (manual).' :" "? 'Sent by AIA (test outbox).' :"
run manual-counts-changed-words api/_lc-engine.js "if (used && !c.first_response_at) { c.first_response_at = at;" "if (!c.first_response_at) { c.first_response_at = at;"
run metrics-no-manual-flag    api/_lc-engine.js "manual: cards.filter((c) => c.first_response_via === 'manual').length" "manual: 0"
rm -rf "$W"
